[package]
name = "mp3v0fs"
version = "0.1.0"
authors = ["Jared <jared@jaredbeckham.com>"]
edition = "2018"

[dependencies]
claxon = { path = "../claxon", version = "0.4.2"}
id3 = "0.3.0"
libc = "0.2"
lame = "0.1.3"
log = "^0.4.8"
fuse_mt = "0.5.0"
simplelog = "0.5.0"
time = "0.1"
